AllCops:
  Exclude:
    - 'bin/**/*'
    - 'pkg/**/*'
    - 'sig/**/*'
  TargetRubyVersion: 3.0

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Style/FrozenStringLiteralComment:
  Enabled: false

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Style/ClassAndModuleChildren:
  Enabled: false

# Temporarily turn this off
Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/RescueException:
  Enabled: true

Lint/Debugger:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

# This sets us to use the standard Rails format instead of Rubocop's
# opinionated Ruby style.
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: 'around'
